name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.1'

      - name: Build App
        run: |
          mkdir -p backup
          cp pubspec.yaml backup/
          cp -r lib backup/
          
          cd ..
          flutter create alsaman_app --project-name=alsaman --platforms=android
          
          cd alsaman_app
          rm -rf pubspec.yaml lib
          cp -r ../BASEM-LG/backup/pubspec.yaml .
          cp -r ../BASEM-LG/backup/lib .
          
          flutter pub get
          flutter build apk --release
          
          mkdir -p ../BASEM-LG/build/app/outputs/flutter-apk/
          cp build/app/outputs/flutter-apk/app-release.apk ../BASEM-LG/build/app/outputs/flutter-apk/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ALSAMAN-APK
          path: build/app/outputs/flutter-apk/app-release.apk
